# TERN-CV Vocabularies, hosted in TERN's GraphDB instance
[[catalogs]]
# VirtualGraph is created per catalog, with the name
# https://linked.data.gov.au/dataset/bdr/catalogs/<token>
# So the graph_name set below cannot be the same as the VirtualGraph name
token = "tern-cv"
label = "TERN Vocabularies"
source = "sparql:https://graphdb.tern.org.au/repositories/tern_vocabs_core"
# This is the identifier of the named-graph (RG) this catalog gets loaded into
graph_name = "https://linked.data.gov.au/dataset/bdr/catalogs/tern-cv-rg"
is_graph_db = true  # This is a GraphDB SPARQL endpoint, use <onto:explicit> in SPARQL queries

[[catalogs.vocabularies]] # In TERN-CV catalog
name = "tern-cv"
vann_prefix = "tern-cv"
vann_namespace = "http://linked.data.gov.au/def/tern-cv/"
root_node = ""  # No root node, discover by concept schemes
#root_node = "http://linked.data.gov.au/def/tern-cv"  # Note this is HTTP, not HTTPS, this is intentional
exclude_concept_schemes = ["http://linked.data.gov.au/dataset/bioregion/IBRA7"]
exclude_collections = []
# This is the identifier of the named-graph (RG) this vocabulary gets loaded into
# All Vocabularies (concept schemes) that are loaded from this defintition will share this named-graph
graph_name = "https://linked.data.gov.au/dataset/bdr/catalogs/tern-cv-rg"
# This vocabulary shares the same RG as the tern-cv catalog defintiion


# NRM/EMSA/DAWE Vocabularies, hosted in TERN's GraphDB instance
[[catalogs]]
token = "nrm"
label = "EMSA Vocabularies"
source = "sparql:https://graphdb.tern.org.au/repositories/dawe_vocabs_core"
# This is the identifier of the named-graph (RG) this catalog gets loaded into
graph_name = "https://linked.data.gov.au/dataset/bdr/catalogs/nrm-cv-rg"
is_graph_db = true  # This is a GraphDB SPARQL endpoint, use <onto:explicit> in SPARQL queries

[[catalogs.vocabularies]] # In NRM/EMSA catalog
name = "emsa"
vann_prefix = "emsa-cv"
vann_namespace = "https://linked.data.gov.au/def/nrm/"
root_node = "https://linked.data.gov.au/def/nrm"
# exclude is a blacklist, don't harvest concepts from these schemes or collections
exclude_concept_schemes = ["http://www.neii.gov.au/def/voc/ACLUMP/australian-land-use-and-management-classification/Australian-Land-Use-and-Management-Classification", "http://linked.data.gov.au/dataset/bioregion/IBRA7"]
exclude_collections = ["https://linked.data.gov.au/def/nrm/31a9f83d-9c8b-4d68-8dd7-d1b7a9a4197b",]  # exclude TERN FeatureTypes profile
graph_name = "https://linked.data.gov.au/dataset/bdr/catalogs/nrm-cv-rg"

[[catalogs.vocabularies]] # In NRM/EMSA catalog
name = "ibra7"
root_node = "http://linked.data.gov.au/dataset/bioregion/IBRA7"
vann_prefix = "ibra7-codes"
vann_namespace = "http://linked.data.gov.au/dataset/bioregion/"
include_concept_schemes = ["http://linked.data.gov.au/dataset/bioregion/IBRA7"]


## ACLUMP was moved to linked.data.gov.au
[[catalogs]]
name = "alum"
token = "alum"
source = "sparql:http://vocabs.ardc.edu.au/repository/api/sparql/abares_australian-land-use-and-management-classification_version-8-with-pids"
label = "ALUM Vocabularies"

[[catalogs.vocabularies]]
name = "alum"
keywords = ["land", "use", "management", "classification", "australia"]
themes = []
vann_prefix = "alum"
vann_namespace = "https://linked.data.gov.au/def/alum/"
root_node = "https://linked.data.gov.au/def/alum" # Concept Scheme


## ABIS Vocabularies
[[catalogs]]
token = "abis"
label = "ABIS Vocabularies"
source = ""  # No Catalog-level source, each ABIS Vocabulary has its own source file

[[catalogs.vocabularies]] # ABIS Vocab Themes vocabulary.
name = "abis-themes"
keywords = ["theme", "themes", "abis"]
themes = []
vann_prefix = "abis-vocab-themes"
vann_namespace = "https://linked.data.gov.au/def/abis/vocab-themes/"
root_node = "https://linked.data.gov.au/def/abis/vocab-themes" # Concept Scheme
source = "file:./sources/abis-themes.ttl"


## BDR Vocabularies
[[catalogs]]
token = "bdr-cv"
label = "BDR Vocabularies"
source = ""  # No Source, each BDR Vocab/Register has its own source file

[[catalogs.vocabularies]] # BDR Observable Properties Register (Vocab)
name = "bdr-observable-properties"
keywords = ["properties", "observable properties", "obsprops", "bdr"]
themes = ["https://linked.data.gov.au/def/abis/vocab-themes/observable-properties"]
vann_prefix = "bdr-obsprops"
vann_namespace = "https://linked.data.gov.au/dataset/bdr/obsprops/"
root_node = "https://linked.data.gov.au/dataset/bdr/obsprops" # Concept Scheme
source = "file:./sources/bdr-vocabs/vocabs/obsprops.ttl"

[[catalogs.vocabularies]] # BDR Data Types Register (Vocab)
name = "bdr-datatypes"
keywords = ["data", "datatype", "types", "bdr"]
themes = ["https://linked.data.gov.au/def/abis/vocab-themes/datatypes"]
vann_prefix = "bdr-datatypes"
vann_namespace = "https://linked.data.gov.au/dataset/bdr/datatypes/"
root_node = "https://linked.data.gov.au/dataset/bdr/datatypes" # Concept Scheme
source = "file:./sources/bdr-vocabs/vocabs/datatypes.ttl"

[[catalogs.vocabularies]] # BDR Submitting Organisations Register (Vocab)
name = "bdr-orgs"
keywords = ["submitting", "organisations", "organizations", "orgs", "bdr"]
themes = []
vann_prefix = "bdr-orgs"
vann_namespace = "https://linked.data.gov.au/dataset/bdr/orgs/"
root_node = "https://linked.data.gov.au/dataset/bdr/orgs" # Concept Scheme
source = "file:./sources/bdr-vocabs/vocabs/orgs.ttl"

[[catalogs.vocabularies]] # BDR Submission Manifest Resource Roles (Vocab)
name = "bdr-smrr"
keywords = ["submission", "manifest", "resource", "roles", "bdr"]
themes = []
vann_prefix = "bdr-smrr"
vann_namespace = "https://linked.data.gov.au/dataset/bdr/smrr/"
root_node = "https://linked.data.gov.au/dataset/bdr/smrr" # Concept Scheme
source = "file:./sources/bdr-vocabs/vocabs/smrr.ttl"

[[catalogs.vocabularies]] # BDR Submission Manifest Resource Roles (Vocab)
name = "bdr-sma"
keywords = ["submission", "manifest", "actions", "bdr"]
themes = []
vann_prefix = "bdr-sma"
vann_namespace = "https://linked.data.gov.au/dataset/bdr/sma/"
root_node = "https://linked.data.gov.au/dataset/bdr/sma" # Concept Scheme
source = "file:./sources/bdr-vocabs/vocabs/sma.ttl"

[[catalogs.vocabularies]] # AGLDWG Data Roles Vocabulary
name = "data-roles"
keywords = ["data", "roles", "agldwg"]
themes = ["https://linked.data.gov.au/def/abis/vocab-themes/data-roles"]
vann_prefix = "data-roles"
vann_namespace = "https://linked.data.gov.au/def/data-roles/"
root_node = "https://linked.data.gov.au/def/data-roles" # Concept Scheme
# This is an example of a HTTPS source, loaded from the web
source = "https://agldwg.github.io/data-roles/vocabulary.ttl"


[[catalogs.namespaces]]
# top-level BDR-Dataset namespace
name = "bdr-ds"
vann_prefix = "bdr-ds"
vann_namespace = "https://linked.data.gov.au/dataset/bdr/"

[[catalogs]]
token = "asls"
label = "ASLS Vocabularies"
source = ""

[[catalogs.vocabularies]]
name = "asls-vegetation"
label = "ASLS Vegetation classifiers (3ed)"
source = "sparql:https://vocabs.ardc.edu.au/repository/api/sparql/csiro_asls-vegetation-classifiers_3ed"
root_node = "http://anzsoil.org/def/au/asls/vegetation" # concept scheme

[[catalogs.vocabularies]]
name = "asls-location"
label = "ASLS Location classifiers (3ed)"
source = "sparql:http://vocabs.ardc.edu.au/repository/api/sparql/csiro_asls-location-classifiers_3ed"
root_node = "http://anzsoil.org/def/au/asls/location" # concept scheme

[[catalogs.vocabularies]]
name = "asls-landform"
label = "ASLS Landform classifiers (3ed)"
source = "sparql:http://vocabs.ardc.edu.au/repository/api/sparql/csiro_landform-classifiers_3ed"
root_node = "http://anzsoil.org/def/au/asls/landform" # concept scheme

[[catalogs.vocabularies]]
name = "asls-land-surface"
label = "ASLS Land Surface classifiers (3ed)"
source = "sparql:http://vocabs.ardc.edu.au/repository/api/sparql/csiro_land-surface-classifiers_3ed"
root_node = "http://anzsoil.org/def/au/asls/land-surface" # concept scheme

[[catalogs.vocabularies]]
name = "asls-soil-prof"
label = "ASLS Soil Profile classifiers (3ed)"
source = "sparql:http://vocabs.ardc.edu.au/repository/api/sparql/csiro-ansis_soil-profile-classifiers_3ed"
root_node = "http://anzsoil.org/def/au/asls/soil-profile" # concept scheme

[[catalogs.vocabularies]]
name = "asls-substrate"
label = "ASLS Substrate classifiers (3ed)"
source = "sparql:http://vocabs.ardc.edu.au/repository/api/sparql/csiro_asls-substrate-classifiers_3ed"
root_node = "http://anzsoil.org/def/au/asls/substrate" # concept scheme


[extra_keywords_mappings]
# Manually map ConceptScheme IDs or Collection IDs to extra keywords
"http://linked.data.gov.au/def/tern-cv/dd085299-ae86-4371-ae15-61dfa432f924" = ["attributes"]  # Attributes ConceptScheme
"http://linked.data.gov.au/def/tern-cv/6ea67eea-c2ae-4240-952a-fdb95b2df8ab" = ["conservation", "jurisdictions"]  # Conservation Status Jurisdictions ConceptScheme
"http://linked.data.gov.au/def/tern-cv/701a9a6d-f67e-4098-bae9-07ce1fd0ce63" = ["data", "resolution"] # Data resolution ConceptScheme
"http://linked.data.gov.au/def/tern-cv/68af3d25-c801-4089-afff-cf701e2bd61d" = ["feature", "type"] # Feature Type ConceptScheme

[extra_themes_mappings]
# Manually map ConceptScheme IDs to extra ABIS Vocab-Themes
"http://linked.data.gov.au/def/tern-cv/68af3d25-c801-4089-afff-cf701e2bd61d" = ["https://linked.data.gov.au/def/abis/vocab-themes/feature-types"]
